// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fishing.proto

package pbTest

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-timeEx assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 通用消息回应
type RespComm struct {
	Errcode              int32    `protobuf:"varint,1,opt,name=errcode,proto3" json:"errcode,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespComm) Reset()         { *m = RespComm{} }
func (m *RespComm) String() string { return proto.CompactTextString(m) }
func (*RespComm) ProtoMessage()    {}
func (*RespComm) Descriptor() ([]byte, []int) {
	return fileDescriptor_7421958bbdf8cbcd, []int{0}
}

func (m *RespComm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespComm.Unmarshal(m, b)
}
func (m *RespComm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespComm.Marshal(b, m, deterministic)
}
func (m *RespComm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespComm.Merge(m, src)
}
func (m *RespComm) XXX_Size() int {
	return xxx_messageInfo_RespComm.Size(m)
}
func (m *RespComm) XXX_DiscardUnknown() {
	xxx_messageInfo_RespComm.DiscardUnknown(m)
}

var xxx_messageInfo_RespComm proto.InternalMessageInfo

func (m *RespComm) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *RespComm) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// 0x1000心跳
type ReqHeartbeat struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqHeartbeat) Reset()         { *m = ReqHeartbeat{} }
func (m *ReqHeartbeat) String() string { return proto.CompactTextString(m) }
func (*ReqHeartbeat) ProtoMessage()    {}
func (*ReqHeartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_7421958bbdf8cbcd, []int{1}
}

func (m *ReqHeartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqHeartbeat.Unmarshal(m, b)
}
func (m *ReqHeartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqHeartbeat.Marshal(b, m, deterministic)
}
func (m *ReqHeartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqHeartbeat.Merge(m, src)
}
func (m *ReqHeartbeat) XXX_Size() int {
	return xxx_messageInfo_ReqHeartbeat.Size(m)
}
func (m *ReqHeartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqHeartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_ReqHeartbeat proto.InternalMessageInfo

func (m *ReqHeartbeat) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// 0x1001
type RespHeartbeat struct {
	Errcode              int32    `protobuf:"varint,1,opt,name=errcode,proto3" json:"errcode,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	T                    *TagTest `protobuf:"bytes,4,opt,name=t,proto3" json:"t,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RespHeartbeat) Reset()         { *m = RespHeartbeat{} }
func (m *RespHeartbeat) String() string { return proto.CompactTextString(m) }
func (*RespHeartbeat) ProtoMessage()    {}
func (*RespHeartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_7421958bbdf8cbcd, []int{2}
}

func (m *RespHeartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RespHeartbeat.Unmarshal(m, b)
}
func (m *RespHeartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RespHeartbeat.Marshal(b, m, deterministic)
}
func (m *RespHeartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RespHeartbeat.Merge(m, src)
}
func (m *RespHeartbeat) XXX_Size() int {
	return xxx_messageInfo_RespHeartbeat.Size(m)
}
func (m *RespHeartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_RespHeartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_RespHeartbeat proto.InternalMessageInfo

func (m *RespHeartbeat) GetErrcode() int32 {
	if m != nil {
		return m.Errcode
	}
	return 0
}

func (m *RespHeartbeat) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RespHeartbeat) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *RespHeartbeat) GetT() *TagTest {
	if m != nil {
		return m.T
	}
	return nil
}

type TagTest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TagTest) Reset()         { *m = TagTest{} }
func (m *TagTest) String() string { return proto.CompactTextString(m) }
func (*TagTest) ProtoMessage()    {}
func (*TagTest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7421958bbdf8cbcd, []int{3}
}

func (m *TagTest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TagTest.Unmarshal(m, b)
}
func (m *TagTest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TagTest.Marshal(b, m, deterministic)
}
func (m *TagTest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TagTest.Merge(m, src)
}
func (m *TagTest) XXX_Size() int {
	return xxx_messageInfo_TagTest.Size(m)
}
func (m *TagTest) XXX_DiscardUnknown() {
	xxx_messageInfo_TagTest.DiscardUnknown(m)
}

var xxx_messageInfo_TagTest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RespComm)(nil), "pbTest.RespComm")
	proto.RegisterType((*ReqHeartbeat)(nil), "pbTest.ReqHeartbeat")
	proto.RegisterType((*RespHeartbeat)(nil), "pbTest.RespHeartbeat")
	proto.RegisterType((*TagTest)(nil), "pbTest.tagTest")
}

func init() { proto.RegisterFile("fishing.proto", fileDescriptor_7421958bbdf8cbcd) }

var fileDescriptor_7421958bbdf8cbcd = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xcb, 0x2c, 0xce,
	0xc8, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0x48, 0x0a, 0x49, 0x2d,
	0x2e, 0x51, 0x32, 0xe3, 0xe2, 0x08, 0x4a, 0x2d, 0x2e, 0x70, 0xce, 0xcf, 0xcd, 0x15, 0x92, 0xe0,
	0x62, 0x4f, 0x2d, 0x2a, 0x4a, 0xce, 0x4f, 0x49, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82,
	0x71, 0x85, 0x04, 0xb8, 0x98, 0x73, 0x8b, 0xd3, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x40,
	0x4c, 0x25, 0x1d, 0x2e, 0x9e, 0xa0, 0xd4, 0x42, 0x8f, 0xd4, 0xc4, 0xa2, 0x92, 0xa4, 0xd4, 0xc4,
	0x12, 0x21, 0x19, 0x2e, 0xce, 0x92, 0xcc, 0xdc, 0xd4, 0xe2, 0x92, 0xc4, 0xdc, 0x02, 0xb0, 0x6e,
	0xe6, 0x20, 0x84, 0x80, 0x52, 0x05, 0x17, 0x2f, 0xc8, 0x16, 0x84, 0x72, 0x12, 0xac, 0x42, 0x35,
	0x9a, 0x19, 0xcd, 0x68, 0x21, 0x59, 0x2e, 0xc6, 0x12, 0x09, 0x16, 0x05, 0x46, 0x0d, 0x6e, 0x23,
	0x7e, 0x3d, 0x88, 0xa7, 0xf4, 0x4a, 0x12, 0xd3, 0x41, 0x74, 0x10, 0x63, 0x89, 0x12, 0x27, 0x17,
	0x3b, 0x94, 0x97, 0xc4, 0x06, 0xf6, 0xb9, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x52, 0xe6, 0xf7,
	0x77, 0x0a, 0x01, 0x00, 0x00,
}
